/**
 * Seed Data — Base operativa de Somos Sinergia.
 * 20 servicios, documentación, checklists, 10 agentes, 13 reglas email, partners base.
 * Ejecutar vía /api/ops-config/seed o importar desde tests.
 */

import type {
  NewServiceCatalogItem, NewServiceDocument, NewServiceChecklist,
  NewEmailRule, NewPartner, NewAgentConfigItem,
} from "@/db/schema";

// ═══════════════════════════════════════════════════════════════
//  CATÁLOGO DE 20 SERVICIOS
// ═══════════════════════════════════════════════════════════════

type ServiceSeed = Omit<NewServiceCatalogItem, "userId"> & { _docs: Omit<NewServiceDocument, "serviceId">[]; _tasks: Omit<NewServiceChecklist, "serviceId">[] };

export const SERVICES: ServiceSeed[] = [
  // ── ENERGÍA (1-4) ──
  {
    name: "Cambio comercializadora luz hogar", vertical: "energia", subtype: "hogar",
    active: true, clientType: "particular", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 30, commissionRecurring: 3,
    agentOwner: "comercial-junior", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 1,
    commercialDescription: "Cambio de comercializadora eléctrica para hogares. Sin coste para el cliente, comisión de partner.",
    internalNotes: "Verificar siempre que el cliente no tenga permanencia activa.",
    _docs: [
      { documentName: "DNI titular", mandatory: true, appliesToClient: "particular", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 1 },
      { documentName: "Factura reciente luz", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 2 },
      { documentName: "CUPS", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 3 },
      { documentName: "IBAN", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "finanzas", sortOrder: 4 },
    ],
    _tasks: [
      { taskName: "Pedir factura reciente al cliente", sortOrder: 1, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Validar CUPS y datos suministro", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "inicio" },
      { taskName: "Revisar potencia contratada", sortOrder: 3, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Comprobar titularidad", sortOrder: 4, mandatory: true, agentResponsible: "recepcion", flowMoment: "proceso" },
      { taskName: "Enviar documentación a partner", sortOrder: 5, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "proceso" },
      { taskName: "Confirmar activación con partner", sortOrder: 6, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "cierre" },
    ],
  },
  {
    name: "Cambio comercializadora luz pyme", vertical: "energia", subtype: "pyme",
    active: true, clientType: "todos", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 60, commissionRecurring: 8,
    agentOwner: "comercial-principal", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 2,
    commercialDescription: "Cambio de comercializadora para pymes y autónomos. Análisis de consumo incluido.",
    internalNotes: "Pedir mínimo 3 facturas para análisis real. Potencia >15kW = tarifa 3.0.",
    _docs: [
      { documentName: "CIF / DNI autónomo", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 1 },
      { documentName: "3 facturas recientes", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 2 },
      { documentName: "CUPS", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 3 },
      { documentName: "IBAN", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "finanzas", sortOrder: 4 },
      { documentName: "Escrituras / contrato alquiler", mandatory: false, appliesToClient: "empresa", requestedBy: "recepcion", reviewedBy: "legal", sortOrder: 5 },
    ],
    _tasks: [
      { taskName: "Solicitar 3 facturas recientes", sortOrder: 1, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Análisis de consumo y potencia", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Comparativa tarifaria", sortOrder: 3, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Presentar propuesta al cliente", sortOrder: 4, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "proceso" },
      { taskName: "Enviar a partner tras aceptación", sortOrder: 5, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
      { taskName: "Confirmar activación", sortOrder: 6, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
    ],
  },
  {
    name: "Optimización de potencia", vertical: "energia", subtype: "optimizacion",
    active: true, clientType: "todos", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 20, commissionRecurring: 0,
    agentOwner: "consultor-servicios", agentSupport: "comercial-junior", requiresDocs: true, sortOrder: 3,
    commercialDescription: "Ajuste de potencia contratada para reducir costes fijos sin cambiar de comercializadora.",
    internalNotes: "Requiere lectura de maxímetro o curva de carga si >15kW.",
    _docs: [
      { documentName: "Factura reciente", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 1 },
      { documentName: "CUPS", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Obtener factura y CUPS", sortOrder: 1, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Analizar potencia real vs contratada", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Generar recomendación", sortOrder: 3, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Tramitar cambio de potencia", sortOrder: 4, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "cierre" },
    ],
  },
  {
    name: "Revisión de renovación energética", vertical: "energia", subtype: "renovacion",
    active: true, clientType: "todos", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 40, commissionRecurring: 5,
    agentOwner: "consultor-servicios", agentSupport: "comercial-principal", requiresDocs: true, sortOrder: 4,
    commercialDescription: "Revisión de contratos energéticos próximos a vencer para negociar mejores condiciones.",
    internalNotes: "Alerta automática 60 días antes de vencimiento. Usar herramienta de renovaciones del CRM.",
    _docs: [
      { documentName: "Contrato actual", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 1 },
      { documentName: "Factura reciente", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Revisar contrato actual y vencimiento", sortOrder: 1, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "inicio" },
      { taskName: "Solicitar ofertas a partners", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Presentar comparativa", sortOrder: 3, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "proceso" },
      { taskName: "Ejecutar cambio o renovación", sortOrder: 4, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
    ],
  },
  // ── TELECOMUNICACIONES (5-8) ──
  {
    name: "Fibra + móvil particular", vertical: "telecomunicaciones", subtype: "particular",
    active: true, clientType: "particular", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 40, commissionRecurring: 5,
    agentOwner: "comercial-junior", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 5,
    commercialDescription: "Pack fibra + móvil para hogares. Sin coste, comisión de operador.",
    internalNotes: "Verificar cobertura fibra antes de ofrecer.",
    _docs: [
      { documentName: "DNI titular", mandatory: true, appliesToClient: "particular", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Factura actual operador", mandatory: false, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 2 },
      { documentName: "IBAN", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "finanzas", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Verificar cobertura fibra", sortOrder: 1, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "inicio" },
      { taskName: "Recoger datos y portabilidad", sortOrder: 2, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Enviar alta a operador", sortOrder: 3, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "proceso" },
      { taskName: "Confirmar instalación", sortOrder: 4, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "cierre" },
    ],
  },
  {
    name: "Fibra + móvil autónomo", vertical: "telecomunicaciones", subtype: "autonomo",
    active: true, clientType: "autonomo", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 50, commissionRecurring: 6,
    agentOwner: "comercial-junior", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 6,
    commercialDescription: "Conectividad para autónomos: fibra + línea móvil profesional.",
    internalNotes: "Ofrecer IP fija si tiene servidor o cámaras.",
    _docs: [
      { documentName: "DNI + alta autónomo", mandatory: true, appliesToClient: "autonomo", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "IBAN", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "finanzas", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Verificar cobertura", sortOrder: 1, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "inicio" },
      { taskName: "Alta y portabilidad", sortOrder: 2, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "proceso" },
      { taskName: "Confirmar activación", sortOrder: 3, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "cierre" },
    ],
  },
  {
    name: "Teleco pyme multi-línea", vertical: "telecomunicaciones", subtype: "pyme",
    active: true, clientType: "empresa", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 80, commissionRecurring: 12,
    agentOwner: "comercial-principal", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 7,
    commercialDescription: "Solución multi-línea para pymes: fibra, líneas fijas, móviles corporativos.",
    internalNotes: "Pedir inventario de líneas actual. Mínimo 3 líneas para tarifa empresa.",
    _docs: [
      { documentName: "CIF empresa", mandatory: true, appliesToClient: "empresa", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Inventario de líneas actual", mandatory: true, appliesToClient: "empresa", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 2 },
      { documentName: "IBAN", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "finanzas", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Recoger inventario de líneas", sortOrder: 1, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "inicio" },
      { taskName: "Diseñar propuesta multi-línea", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Negociar con operador", sortOrder: 3, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "proceso" },
      { taskName: "Ejecutar migración", sortOrder: 4, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
    ],
  },
  {
    name: "Centralita / conectividad empresa", vertical: "telecomunicaciones", subtype: "empresa",
    active: true, clientType: "empresa", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 120, commissionRecurring: 20,
    agentOwner: "comercial-principal", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 8,
    commercialDescription: "Centralita virtual + conectividad profesional para empresas.",
    internalNotes: "Proyecto técnico. Coordinar con partner de centralita.",
    _docs: [
      { documentName: "CIF", mandatory: true, appliesToClient: "empresa", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Inventario líneas y extensiones", mandatory: true, appliesToClient: "empresa", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Auditoría telecomunicaciones actual", sortOrder: 1, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "inicio" },
      { taskName: "Diseñar solución centralita", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Presentar propuesta", sortOrder: 3, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "proceso" },
      { taskName: "Coordinar instalación", sortOrder: 4, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
    ],
  },
  // ── SEGUROS (9-11) ──
  {
    name: "Seguro hogar", vertical: "seguros", subtype: "hogar",
    active: true, clientType: "particular", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 25, commissionRecurring: 0,
    agentOwner: "comercial-junior", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 9,
    commercialDescription: "Seguro de hogar con las mejores coberturas del mercado.",
    internalNotes: "Pedir póliza actual si tiene. Comparar siempre 3 aseguradoras.",
    _docs: [
      { documentName: "DNI", mandatory: true, appliesToClient: "particular", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Póliza actual (si tiene)", mandatory: false, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Recoger datos del hogar", sortOrder: 1, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Comparativa aseguradoras", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Presentar opciones", sortOrder: 3, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "proceso" },
      { taskName: "Tramitar póliza", sortOrder: 4, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "cierre" },
    ],
  },
  {
    name: "Seguro comercio / pyme", vertical: "seguros", subtype: "comercio",
    active: true, clientType: "empresa", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 50, commissionRecurring: 0,
    agentOwner: "comercial-principal", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 10,
    commercialDescription: "Seguro multirriesgo para comercios y pymes.",
    internalNotes: "Incluir RC obligatoria. Verificar actividad económica.",
    _docs: [
      { documentName: "CIF", mandatory: true, appliesToClient: "empresa", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Póliza actual", mandatory: false, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "consultor-servicios", sortOrder: 2 },
      { documentName: "Licencia actividad", mandatory: false, appliesToClient: "empresa", requestedBy: "recepcion", reviewedBy: "legal", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Recoger datos del negocio", sortOrder: 1, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Solicitar cotizaciones", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Negociar condiciones", sortOrder: 3, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "proceso" },
      { taskName: "Formalizar póliza", sortOrder: 4, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
    ],
  },
  {
    name: "Seguro salud / colectivo pequeño", vertical: "seguros", subtype: "salud",
    active: true, clientType: "todos", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 35, commissionRecurring: 0,
    agentOwner: "comercial-principal", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 11,
    commercialDescription: "Seguro de salud individual o colectivo para pequeñas empresas.",
    internalNotes: "Colectivo mínimo 3 personas. Verificar cuadro médico por zona.",
    _docs: [
      { documentName: "DNI de cada asegurado", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Cuestionario de salud", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Recoger datos asegurados", sortOrder: 1, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Cotizar con aseguradoras", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Presentar opciones", sortOrder: 3, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "proceso" },
      { taskName: "Formalizar póliza", sortOrder: 4, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
    ],
  },
  // ── ALARMAS (12-13) ──
  {
    name: "Alarma hogar", vertical: "alarmas", subtype: "hogar",
    active: true, clientType: "particular", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 50, commissionRecurring: 8,
    agentOwner: "comercial-junior", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 12,
    commercialDescription: "Sistema de alarma para hogar con conexión a CRA.",
    internalNotes: "Partner gestiona instalación. Nosotros cerramos la venta.",
    _docs: [
      { documentName: "DNI", mandatory: true, appliesToClient: "particular", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Dirección instalación", mandatory: true, appliesToClient: "todos", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Recoger datos y dirección", sortOrder: 1, mandatory: true, agentResponsible: "recepcion", flowMoment: "inicio" },
      { taskName: "Verificar zona y cobertura", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Enviar pedido a partner", sortOrder: 3, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "cierre" },
      { taskName: "Confirmar instalación", sortOrder: 4, mandatory: true, agentResponsible: "comercial-junior", flowMoment: "postventa" },
    ],
  },
  {
    name: "Alarma negocio", vertical: "alarmas", subtype: "negocio",
    active: true, clientType: "empresa", economicModel: "partner",
    priceSetup: 0, priceMonthly: 0, commissionFixed: 80, commissionRecurring: 12,
    agentOwner: "comercial-principal", agentSupport: "consultor-servicios", requiresDocs: true, sortOrder: 13,
    commercialDescription: "Alarma para negocio con videovigilancia y conexión CRA.",
    internalNotes: "Valorar sistema CCTV integrado si hay más de 100m2.",
    _docs: [
      { documentName: "CIF", mandatory: true, appliesToClient: "empresa", requestedBy: "recepcion", reviewedBy: "recepcion", sortOrder: 1 },
      { documentName: "Plano local", mandatory: false, appliesToClient: "empresa", requestedBy: "consultor-servicios", reviewedBy: "consultor-servicios", sortOrder: 2 },
    ],
    _tasks: [
      { taskName: "Visita o recogida de datos del local", sortOrder: 1, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "inicio" },
      { taskName: "Diseñar sistema de seguridad", sortOrder: 2, mandatory: true, agentResponsible: "consultor-servicios", flowMoment: "proceso" },
      { taskName: "Presentar propuesta", sortOrder: 3, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "proceso" },
      { taskName: "Coordinar instalación", sortOrder: 4, mandatory: true, agentResponsible: "comercial-principal", flowMoment: "cierre" },
    ],
  },
  // ── IA (14-15) — solo autónomo y empresa ──
  {
    name: "Agente IA básico", vertical: "ia", subtype: "basico",
    active: true, clientType: "empresa", economicModel: "directo",
    priceSetup: 1500, priceMonthly: 200, commissionFixed: 0, commissionRecurring: 0,
    agentOwner: "consultor-digital", agentSupport: "ceo", requiresDocs: true, sortOrder: 14,
    commercialDescription: "Agente de IA personalizado para atención al cliente, FAQ o soporte interno.",
    internalNotes: "Reunión de alcance obligatoria. Entregar en 2-3 semanas.",
    _docs: [
      { documentName: "Proceso actual documentado", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 1 },
      { documentName: "Emails / conversaciones ejemplo", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 2 },
      { documentName: "Alcance funcional firmado", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "ceo", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Recoger proceso actual", sortOrder: 1, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Recoger emails ejemplo", sortOrder: 2, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Definir objetivo y KPIs", sortOrder: 3, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Diseñar flujo del agente", sortOrder: 4, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Validar canales de integración", sortOrder: 5, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Lanzar setup y testing", sortOrder: 6, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "cierre" },
    ],
  },
  {
    name: "Automatización IA documental", vertical: "ia", subtype: "documental",
    active: true, clientType: "empresa", economicModel: "directo",
    priceSetup: 2500, priceMonthly: 300, commissionFixed: 0, commissionRecurring: 0,
    agentOwner: "consultor-digital", agentSupport: "ceo", requiresDocs: true, sortOrder: 15,
    commercialDescription: "Automatización de procesos documentales con IA: facturas, contratos, informes.",
    internalNotes: "Proyecto técnico. Reunión con CEO si >5000€.",
    _docs: [
      { documentName: "Muestras documentales", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 1 },
      { documentName: "Descripción del flujo actual", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 2 },
      { documentName: "Alcance funcional firmado", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "ceo", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Recoger muestras documentales", sortOrder: 1, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Mapear flujo actual", sortOrder: 2, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Diseñar automatización", sortOrder: 3, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Desarrollo e integración", sortOrder: 4, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Testing con datos reales", sortOrder: 5, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "cierre" },
      { taskName: "Entrega y formación", sortOrder: 6, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "postventa" },
    ],
  },
  // ── WEB (16-17) ──
  {
    name: "Web corporativa básica", vertical: "web", subtype: "basica",
    active: true, clientType: "empresa", economicModel: "directo",
    priceSetup: 900, priceMonthly: 50, commissionFixed: 0, commissionRecurring: 0,
    agentOwner: "consultor-digital", agentSupport: "marketing", requiresDocs: true, sortOrder: 16,
    commercialDescription: "Web corporativa profesional: diseño, hosting, dominio, adaptada a móvil.",
    internalNotes: "Entregar en 2-3 semanas. Hosting incluido en mensualidad.",
    _docs: [
      { documentName: "Logo en alta resolución", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 1 },
      { documentName: "Textos y contenidos", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "marketing", sortOrder: 2 },
      { documentName: "Fotos del negocio", mandatory: false, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Recoger briefing y materiales", sortOrder: 1, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Diseño y maquetación", sortOrder: 2, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Revisión con cliente", sortOrder: 3, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Publicación y entrega", sortOrder: 4, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "cierre" },
    ],
  },
  {
    name: "Web + SEO local", vertical: "web", subtype: "seo",
    active: true, clientType: "empresa", economicModel: "directo",
    priceSetup: 1500, priceMonthly: 150, commissionFixed: 0, commissionRecurring: 0,
    agentOwner: "consultor-digital", agentSupport: "marketing", requiresDocs: true, sortOrder: 17,
    commercialDescription: "Web profesional + posicionamiento SEO local para captar clientes en tu zona.",
    internalNotes: "SEO local = Google My Business + optimización on-page + contenido mensual.",
    _docs: [
      { documentName: "Logo", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 1 },
      { documentName: "Textos", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "marketing", sortOrder: 2 },
      { documentName: "Accesos Google My Business", mandatory: true, appliesToClient: "todos", requestedBy: "marketing", reviewedBy: "marketing", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Briefing y materiales", sortOrder: 1, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Diseño web + SEO base", sortOrder: 2, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Configurar Google My Business", sortOrder: 3, mandatory: true, agentResponsible: "marketing", flowMoment: "proceso" },
      { taskName: "Lanzar y monitorizar", sortOrder: 4, mandatory: true, agentResponsible: "marketing", flowMoment: "cierre" },
    ],
  },
  // ── MARKETING (18) ──
  {
    name: "Marketing recurrente / redes + contenido", vertical: "marketing", subtype: "recurrente",
    active: true, clientType: "empresa", economicModel: "directo",
    priceSetup: 300, priceMonthly: 400, commissionFixed: 0, commissionRecurring: 0,
    agentOwner: "marketing", agentSupport: "consultor-digital", requiresDocs: true, sortOrder: 18,
    commercialDescription: "Gestión mensual de redes sociales + contenido + campañas.",
    internalNotes: "Mínimo compromiso 3 meses. Reportes mensuales.",
    _docs: [
      { documentName: "Accesos redes sociales", mandatory: true, appliesToClient: "todos", requestedBy: "marketing", reviewedBy: "marketing", sortOrder: 1 },
      { documentName: "Logo y línea gráfica", mandatory: true, appliesToClient: "todos", requestedBy: "marketing", reviewedBy: "consultor-digital", sortOrder: 2 },
      { documentName: "Brief de marca", mandatory: false, appliesToClient: "todos", requestedBy: "marketing", reviewedBy: "marketing", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Recoger accesos y materiales", sortOrder: 1, mandatory: true, agentResponsible: "marketing", flowMoment: "inicio" },
      { taskName: "Crear calendario editorial", sortOrder: 2, mandatory: true, agentResponsible: "marketing", flowMoment: "proceso" },
      { taskName: "Aprobar primeros contenidos", sortOrder: 3, mandatory: true, agentResponsible: "marketing", flowMoment: "proceso" },
      { taskName: "Lanzar y reportar", sortOrder: 4, mandatory: true, agentResponsible: "marketing", flowMoment: "cierre" },
    ],
  },
  // ── CRM (19) ──
  {
    name: "Implantación CRM", vertical: "crm", subtype: "implantacion",
    active: true, clientType: "empresa", economicModel: "directo",
    priceSetup: 2000, priceMonthly: 150, commissionFixed: 0, commissionRecurring: 0,
    agentOwner: "consultor-digital", agentSupport: "ceo", requiresDocs: true, sortOrder: 19,
    commercialDescription: "Implantación de CRM adaptado al negocio: configuración, migración, formación.",
    internalNotes: "Reunión de alcance + demo obligatoria antes de presupuesto.",
    _docs: [
      { documentName: "Proceso comercial actual", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 1 },
      { documentName: "Base de datos actual (Excel/CSV)", mandatory: false, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 2 },
      { documentName: "Alcance funcional", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "ceo", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Reunión de alcance", sortOrder: 1, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Demo y validación", sortOrder: 2, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Configuración y migración", sortOrder: 3, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Formación equipo", sortOrder: 4, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "cierre" },
      { taskName: "Seguimiento post-implantación", sortOrder: 5, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "postventa" },
    ],
  },
  // ── APPS (20) ──
  {
    name: "Web app / app operativa", vertical: "apps", subtype: "operativa",
    active: true, clientType: "empresa", economicModel: "directo",
    priceSetup: 5000, priceMonthly: 400, commissionFixed: 0, commissionRecurring: 0,
    agentOwner: "consultor-digital", agentSupport: "ceo", requiresDocs: true, sortOrder: 20,
    commercialDescription: "Desarrollo de aplicación web a medida para operaciones internas o clientes.",
    internalNotes: "Proyecto complejo. Requiere validación CEO. Mínimo 6 semanas.",
    _docs: [
      { documentName: "Alcance funcional detallado", mandatory: true, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "ceo", sortOrder: 1 },
      { documentName: "Wireframes / mockups", mandatory: false, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 2 },
      { documentName: "Datos de integración", mandatory: false, appliesToClient: "todos", requestedBy: "consultor-digital", reviewedBy: "consultor-digital", sortOrder: 3 },
    ],
    _tasks: [
      { taskName: "Reunión de alcance funcional", sortOrder: 1, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "inicio" },
      { taskName: "Diseño UX/UI", sortOrder: 2, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Desarrollo iterativo", sortOrder: 3, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Testing y ajustes", sortOrder: 4, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "proceso" },
      { taskName: "Despliegue y formación", sortOrder: 5, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "cierre" },
      { taskName: "Soporte post-lanzamiento", sortOrder: 6, mandatory: true, agentResponsible: "consultor-digital", flowMoment: "postventa" },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════
//  10 AGENTES
// ═══════════════════════════════════════════════════════════════

export const AGENTS: Omit<NewAgentConfigItem, "userId">[] = [
  { agentSlug: "recepcion", displayName: "Recepción", role: "Puerta de entrada, triaje y delegación",
    description: "Clasifica todo lo que entra (email, llamada, formulario). Limpia ruido, extrae adjuntos, identifica remitente/cliente/proveedor y delega al agente correcto. No vende directamente.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas","ia","web","marketing","crm","apps"],
    clientTypes: ["particular","autonomo","empresa"],
    canDo: ["clasificar emails","extraer adjuntos","identificar clientes","proponer alta de empresa","delegar a agentes","crear tareas de recogida documental"],
    cannotDo: ["vender","negociar precios","firmar contratos","tomar decisiones comerciales"],
    servicesOwner: [], servicesSupport: ["todos"],
    taskTypes: ["triaje","recogida_documental","alta_empresa","delegacion"],
    specialRules: "No todo correo va a comercial. Publicidad y spam se silencian. Facturas energéticas van a energía, no a comercial.",
  },
  { agentSlug: "comercial-junior", displayName: "Comercial Junior", role: "Ventas particular + autónomo simple + seguimiento",
    description: "Cierra ventas simples para particulares y autónomos. Seguimiento documental. Coordina con partners.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas"],
    clientTypes: ["particular","autonomo"],
    canDo: ["cerrar ventas simples","seguimiento documental","enviar a partners","confirmar activaciones","registrar actividades"],
    cannotDo: ["negociar precios especiales","cerrar empresa grande","modificar comisiones","aprobar excepciones"],
    servicesOwner: ["Cambio comercializadora luz hogar","Fibra + móvil particular","Fibra + móvil autónomo","Seguro hogar","Alarma hogar"],
    servicesSupport: ["Optimización de potencia"],
    taskTypes: ["venta","seguimiento","documentacion","activacion"],
    specialRules: "Escalar a comercial-principal si el cliente pide multiservicio o negociación.",
  },
  { agentSlug: "comercial-principal", displayName: "Comercial Principal", role: "Empresas + multiservicio + negociación + cierres complejos",
    description: "Gestiona empresas, pymes con negociación, multiservicio. Cierres complejos y relación comercial a largo plazo.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas","ia","web","marketing","crm","apps"],
    clientTypes: ["autonomo","empresa"],
    canDo: ["negociar precios","cerrar multiservicio","gestionar cuentas empresa","coordinar proyectos","aprobar propuestas"],
    cannotDo: ["modificar comisiones de partner","firmar contratos >10K sin CEO","cambiar pricing general"],
    servicesOwner: ["Cambio comercializadora luz pyme","Teleco pyme multi-línea","Centralita / conectividad empresa","Seguro comercio / pyme","Seguro salud / colectivo pequeño","Alarma negocio"],
    servicesSupport: ["Revisión de renovación energética","Agente IA básico","Web corporativa básica"],
    taskTypes: ["venta","negociacion","propuesta","cierre","cuenta"],
    specialRules: "Escalar a CEO si >10K o condiciones especiales de partner.",
  },
  { agentSlug: "consultor-servicios", displayName: "Consultor Servicios", role: "Revisión técnica/comercial: energía, teleco, seguros, alarmas",
    description: "Experto técnico en los 4 verticales de partner. Analiza facturas, diseña soluciones, valida documentación.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas"],
    clientTypes: ["particular","autonomo","empresa"],
    canDo: ["analizar facturas energéticas","comparar tarifas","diseñar soluciones teleco","validar documentación","generar propuestas técnicas","checklist documental"],
    cannotDo: ["cerrar ventas","negociar precios finales","contactar directamente con el cliente sin comercial"],
    servicesOwner: ["Optimización de potencia","Revisión de renovación energética"],
    servicesSupport: ["todos los de partner"],
    taskTypes: ["analisis","revision_tecnica","comparativa","checklist","propuesta_tecnica"],
    specialRules: "Trabaja siempre en apoyo del comercial. No cierra la venta.",
  },
  { agentSlug: "consultor-digital", displayName: "Consultor Digital", role: "IA, web, marketing, CRM, apps — alcance y propuesta",
    description: "Experto en servicios digitales. Define alcance, diseña soluciones, ejecuta proyectos técnicos.",
    verticals: ["ia","web","marketing","crm","apps"],
    clientTypes: ["autonomo","empresa"],
    canDo: ["definir alcance","diseñar soluciones digitales","ejecutar proyectos","presupuestar","formar equipos"],
    cannotDo: ["aprobar proyectos >5K sin CEO","modificar pricing general","gestionar partners de comisión"],
    servicesOwner: ["Agente IA básico","Automatización IA documental","Web corporativa básica","Web + SEO local","Implantación CRM","Web app / app operativa"],
    servicesSupport: ["Marketing recurrente / redes + contenido"],
    taskTypes: ["alcance","propuesta","desarrollo","testing","formacion","entrega"],
    specialRules: "Proyectos >5K requieren validación CEO. Siempre documentar alcance antes de empezar.",
  },
  { agentSlug: "bi-scoring", displayName: "BI / Scoring", role: "Priorización, análisis, valor potencial, riesgo",
    description: "Analiza datos para priorizar leads, evaluar riesgo y calcular valor potencial de clientes.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas","ia","web","marketing","crm","apps"],
    clientTypes: ["particular","autonomo","empresa"],
    canDo: ["scoring de leads","análisis de cartera","priorización","detección cross-sell","predicción churn"],
    cannotDo: ["vender","contactar clientes","tomar decisiones comerciales"],
    servicesOwner: [], servicesSupport: [],
    taskTypes: ["analisis","scoring","reporte","prediccion"],
    specialRules: "Solo análisis y recomendaciones. No acciones directas.",
  },
  { agentSlug: "finanzas", displayName: "Finanzas / Fiscal", role: "Bancos, pagos, cobros, facturas administrativas",
    description: "Gestiona facturación, pagos, cobros, conciliación bancaria y documentación fiscal.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas","ia","web","marketing","crm","apps"],
    clientTypes: ["particular","autonomo","empresa"],
    canDo: ["gestionar facturas","conciliar pagos","generar informes financieros","revisar IBAN","gestionar impagos"],
    cannotDo: ["vender","negociar","modificar precios","acceder a datos comerciales sensibles"],
    servicesOwner: [], servicesSupport: [],
    taskTypes: ["facturacion","cobro","pago","conciliacion","informe_fiscal"],
    specialRules: "Facturas administrativas (no energéticas) van aquí. Las energéticas van a consultor-servicios.",
  },
  { agentSlug: "legal", displayName: "Legal / RGPD", role: "Contratos, protección de datos, revisión delicada",
    description: "Revisa contratos, gestiona RGPD, valida documentación legal, asesora en situaciones delicadas.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas","ia","web","marketing","crm","apps"],
    clientTypes: ["particular","autonomo","empresa"],
    canDo: ["revisar contratos","gestionar RGPD","validar documentación legal","asesorar en disputas"],
    cannotDo: ["vender","negociar comercialmente","aprobar gastos"],
    servicesOwner: [], servicesSupport: [],
    taskTypes: ["revision_contrato","rgpd","asesoria_legal","documentacion_legal"],
    specialRules: "Todo contrato >5K debe pasar por legal antes de firma.",
  },
  { agentSlug: "marketing", displayName: "Marketing", role: "Campañas, nurturing, automatizaciones comerciales",
    description: "Ejecuta campañas, gestiona redes, nurturing de leads, automatizaciones de marketing.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas","ia","web","marketing","crm","apps"],
    clientTypes: ["particular","autonomo","empresa"],
    canDo: ["crear campañas","gestionar redes","email marketing","nurturing","reportes de marketing","contenido"],
    cannotDo: ["cerrar ventas","negociar precios","aprobar presupuestos >1K"],
    servicesOwner: ["Marketing recurrente / redes + contenido"],
    servicesSupport: ["Web + SEO local","Web corporativa básica"],
    taskTypes: ["campana","contenido","redes","nurturing","reporte"],
    specialRules: "Coordinar con consultor-digital para servicios web. No contactar clientes empresa directamente.",
  },
  { agentSlug: "ceo", displayName: "CEO", role: "Reglas, pricing, partners, excepciones, cierres raros",
    description: "Toma decisiones estratégicas, aprueba excepciones, gestiona relación con partners, define pricing.",
    verticals: ["energia","telecomunicaciones","seguros","alarmas","ia","web","marketing","crm","apps"],
    clientTypes: ["particular","autonomo","empresa"],
    canDo: ["aprobar excepciones","modificar pricing","gestionar partners","cerrar acuerdos especiales","definir reglas"],
    cannotDo: [],
    servicesOwner: [], servicesSupport: ["todos"],
    taskTypes: ["aprobacion","pricing","partner","excepcion","estrategia"],
    specialRules: "Solo interviene cuando se escala. No gestiona operativa diaria.",
  },
];

// ═══════════════════════════════════════════════════════════════
//  13 REGLAS DE CORREO BASE
// ═══════════════════════════════════════════════════════════════

export const EMAIL_RULES: Omit<NewEmailRule, "userId">[] = [
  { name: "Publicidad / Newsletter", emailType: "publicidad", senderPattern: "noreply@|newsletter@|marketing@|mailchimp|sendgrid|hubspot|brevo", subjectPattern: "newsletter|boletín|promoción|descuento|oferta|unsubscribe", category: "publicidad", routing: "silenciar", createTask: false, createAlert: false, createCase: false, extractPdf: false, extractExcel: false, saveDocumentation: false, requireConfirmation: false, agentResponsible: "recepcion", priority: "baja", active: true, notes: "Silenciar sin generar actividad CRM" },
  { name: "Spam", emailType: "spam", senderPattern: "", subjectPattern: "", category: "spam", routing: "silenciar", createTask: false, createAlert: false, createCase: false, extractPdf: false, extractExcel: false, saveDocumentation: false, requireConfirmation: false, agentResponsible: "recepcion", priority: "baja", active: true, notes: "Detectado por Gemini. Sin acción." },
  { name: "Factura energética", emailType: "factura_energia", senderPattern: "endesa|iberdrola|naturgy|repsol|holaluz|totalenergies", subjectPattern: "factura.*luz|factura.*energía|CUPS|kWh|potencia", category: "factura_energia", routing: "energia", createTask: false, createAlert: true, createCase: false, extractPdf: true, extractExcel: false, saveDocumentation: true, requireConfirmation: false, agentResponsible: "consultor-servicios", priority: "media", active: true, notes: "Va a energía, NO a comercial" },
  { name: "Factura administrativa", emailType: "factura_admin", senderPattern: "", subjectPattern: "factura.*teléfono|factura.*seguro|recibo|nómina|domiciliación", category: "factura_admin", routing: "finanzas", createTask: false, createAlert: false, createCase: false, extractPdf: true, extractExcel: false, saveDocumentation: true, requireConfirmation: false, agentResponsible: "finanzas", priority: "media", active: true, notes: "Facturas NO energéticas van a finanzas" },
  { name: "Cliente urgente", emailType: "cliente_urgente", senderPattern: "", subjectPattern: "urgente|avería|corte de luz|sin suministro|reclamación|incidencia", category: "cliente_urgente", routing: "comercial", createTask: true, createAlert: true, createCase: false, extractPdf: false, extractExcel: false, saveDocumentation: false, requireConfirmation: false, agentResponsible: "comercial-principal", priority: "alta", active: true, notes: "Tarea URGENTE + actividad" },
  { name: "Cliente normal", emailType: "cliente_normal", senderPattern: "", subjectPattern: "", category: "cliente_normal", routing: "comercial", createTask: false, createAlert: false, createCase: false, extractPdf: false, extractExcel: false, saveDocumentation: false, requireConfirmation: false, agentResponsible: "comercial-principal", priority: "media", active: true, notes: "Log de actividad, sin tarea" },
  { name: "Proveedor estratégico — precios", emailType: "proveedor_estrategico", senderPattern: "tunergia|procesus", subjectPattern: "actualización.*precios|nuevas? tarifas|cambio.*condiciones|vigencia", category: "proveedor_precios", routing: "documentacion", createTask: true, createAlert: true, createCase: false, extractPdf: true, extractExcel: true, saveDocumentation: true, requireConfirmation: false, agentResponsible: "consultor-servicios", priority: "alta", active: true, notes: "Tunergia/Procesus con precios = ESTRATÉGICO" },
  { name: "Proveedor estratégico — general", emailType: "proveedor_estrategico", senderPattern: "tunergia|procesus|endesa|iberdrola|naturgy", subjectPattern: "", category: "proveedor_normal", routing: "recepcion", createTask: false, createAlert: false, createCase: false, extractPdf: false, extractExcel: false, saveDocumentation: false, requireConfirmation: false, agentResponsible: "recepcion", priority: "media", active: true, notes: "Comunicación normal de proveedor estratégico" },
  { name: "Documentación útil", emailType: "documentacion", senderPattern: "", subjectPattern: "contrato|anexo|tarifa|listado|tabla.*datos", category: "documentacion_util", routing: "documentacion", createTask: false, createAlert: true, createCase: false, extractPdf: true, extractExcel: true, saveDocumentation: true, requireConfirmation: false, agentResponsible: "consultor-servicios", priority: "media", active: true, notes: "Extraer adjuntos útiles" },
  { name: "Banco / financiero", emailType: "banco", senderPattern: "bankinter|bbva|santander|caixabank|sabadell|unicaja|ing", subjectPattern: "transferencia|movimiento|extracto|recibo", category: "notificacion_auto", routing: "finanzas", createTask: false, createAlert: false, createCase: false, extractPdf: true, extractExcel: false, saveDocumentation: true, requireConfirmation: false, agentResponsible: "finanzas", priority: "media", active: true, notes: "Notificaciones bancarias a finanzas" },
  { name: "Legal / contrato", emailType: "legal", senderPattern: "", subjectPattern: "contrato|acuerdo|cláusula|protección de datos|RGPD|denuncia", category: "legal_contrato", routing: "legal", createTask: false, createAlert: true, createCase: false, extractPdf: true, extractExcel: false, saveDocumentation: true, requireConfirmation: true, agentResponsible: "legal", priority: "alta", active: true, notes: "Alerta ALTA + requiere confirmación" },
  { name: "Notificación automática", emailType: "notificacion_auto", senderPattern: "noreply@|no-reply@|notifications@|alerts@", subjectPattern: "", category: "notificacion_auto", routing: "log_only", createTask: false, createAlert: false, createCase: false, extractPdf: false, extractExcel: false, saveDocumentation: false, requireConfirmation: false, agentResponsible: "recepcion", priority: "baja", active: true, notes: "SaaS, bancos, plataformas — solo log" },
  { name: "Ambiguo / sin clasificar", emailType: "ambiguo", senderPattern: "", subjectPattern: "", category: "otro", routing: "recepcion", createTask: false, createAlert: false, createCase: false, extractPdf: false, extractExcel: false, saveDocumentation: false, requireConfirmation: true, agentResponsible: "recepcion", priority: "media", active: true, notes: "Requiere clasificación manual" },
];

// ═══════════════════════════════════════════════════════════════
//  PARTNERS BASE
// ═══════════════════════════════════════════════════════════════

export const PARTNERS: Omit<NewPartner, "userId">[] = [
  { name: "Tunergia", vertical: "energia", product: "Comercialización eléctrica", commissionFixed: 30, commissionRecurring: 3, conditions: "Comisión por alta + recurrente mensual durante contrato", clawback: "Devolución si baja antes de 3 meses", requiredDocumentation: "DNI/CIF, factura, CUPS, IBAN", active: true, notes: "Partner principal energía" },
  { name: "Procesus", vertical: "energia", product: "Comercialización eléctrica", commissionFixed: 25, commissionRecurring: 2, conditions: "Comisión por alta + recurrente", clawback: "Devolución si baja antes de 6 meses", requiredDocumentation: "DNI/CIF, factura, CUPS, IBAN", active: true, notes: "Partner secundario energía" },
  { name: "(Operador teleco)", vertical: "telecomunicaciones", product: "Fibra + móvil", commissionFixed: 40, commissionRecurring: 5, conditions: "Por línea activada", clawback: "Penalización si baja antes de 12 meses", requiredDocumentation: "DNI, IBAN", active: true, notes: "Pendiente definir operador concreto" },
  { name: "(Aseguradora)", vertical: "seguros", product: "Seguros multirriesgo y salud", commissionFixed: 25, commissionRecurring: 0, conditions: "Comisión por póliza emitida", clawback: "Sin clawback si prima pagada", requiredDocumentation: "DNI, cuestionario salud si aplica", active: true, notes: "Pendiente definir aseguradora concreta" },
  { name: "(Empresa alarmas)", vertical: "alarmas", product: "Sistemas de alarma + CRA", commissionFixed: 50, commissionRecurring: 8, conditions: "Comisión por instalación + recurrente mientras el cliente mantenga servicio", clawback: "Devolución si baja antes de 12 meses", requiredDocumentation: "DNI/CIF, dirección instalación", active: true, notes: "Pendiente definir empresa concreta" },
];
